title: "Go with Bazel"
summary: |
  この本では、Go言語とBazelを使ってモノレポを構築する方法を解説します。
  Bazelはオープンソースのビルドツールです。MavenやGradleのようなツールですが、日本で採用している企業は少なく、最新の使い方を解説した日本語の情報はほとんどありません。
  そのため難しい・複雑である・扱えないといったイメージをもつ方が多く、実際に導入したもののメンテナンスの難しさから撤退したという話も聞きます。
  少なくともGoをメインに採用する場合、最近のツールの進歩によりBazelを取り扱うことは比較的容易になってきていると感じます。

  この本では、Bazelの基本的な使い方から、Go言語を使ってビルド、テストなどを行い、最終的にビルドしたバイナリをマルチプラットフォームイメージとしてコンテナレジストリに登録するところまでを扱います。
  Bazelはあくまでビルドツールであるため、それらのアーティファクトをどのように本番環境へデプロイするかについては触れません。

  多くの企業では肥大化するソースコード、およびそのビルド・リリースのワークフローに悩まされています。Bazelを使うことで、これらの問題を解決できるかもしれません。
  また、Bazelの世界観に触れることで、自分達の開発プロセスを見直すきっかけになるかもしれません。
  
  ※ 著者は特にBazelの開発者でもなく、企業でのBazelの導入経験もありません。趣味です。
topics: ["Go","Bazel"]
published: false
price: 0
chapters:
  - 01-intro
  - 02-setup
  - 03-go-modules
  - 04-internal-modules
  - 05-unittest
  - 06-lint
